In [67]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [68]:
import numpy as np

In [69]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [70]:
np.random.seed(1000)
np.round(np.random.rand(5,5)*1000)

array([[654., 115., 950., 482., 872.],
       [212.,  41., 397., 233., 842.],
       [207., 742., 392., 182., 744.],
       [ 70., 885., 953., 931., 415.],
       [ 29., 982., 340., 707., 362.]])

In [71]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5)

array([3, 6, 5, 8, 1])

In [72]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5, replace = False)

array([3, 6, 1, 9, 7])

In [73]:
np_matrix = np.random.rand(5,5)
idx_choose = np.random.choice(5,3)
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose

array([[0.84905468, 0.17908859, 0.97449772, 0.90629069, 0.3178783 ],
       [0.74535564, 0.07664517, 0.77987308, 0.19980574, 0.45237551],
       [0.84905468, 0.17908859, 0.97449772, 0.90629069, 0.3178783 ]])

In [74]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[1, 1, 0, 1, 2],
       [1, 2, 0, 2, 0],
       [1, 0, 1, 1, 1],
       [1, 2, 0, 0, 1],
       [2, 0, 1, 2, 1]])

In [75]:
i,j = np.where(np_matrix == 2)

In [76]:
i

array([0, 1, 1, 3, 4, 4])

In [77]:
j

array([4, 1, 3, 1, 0, 3])

In [78]:
data = np.random.randint(5,size=(5,5)) + 1
data

array([[2, 5, 2, 5, 1],
       [3, 2, 1, 5, 4],
       [3, 1, 4, 1, 4],
       [1, 5, 4, 4, 4],
       [4, 5, 5, 3, 5]])

In [79]:
np.max(data,0)

array([4, 5, 5, 5, 5])

In [80]:
np.max(data,1)

array([5, 5, 4, 5, 5])

# Ex2

In [81]:
np_matrix = np.random.rand(5,5)
idx_choose = np.random.choice(5,10)
np_matrix_choose = np_matrix[idx_choose,:]
result = np.round(np_matrix_choose[:,-1])
np_matrix_choose[:,4] = result
np_matrix_choose

array([[0.89283842, 0.18479588, 0.55289879, 0.96149412, 0.        ],
       [0.89283842, 0.18479588, 0.55289879, 0.96149412, 0.        ],
       [0.91537502, 0.26913929, 0.02676   , 0.62181509, 1.        ],
       [0.64934701, 0.0206012 , 0.69027139, 0.64615704, 1.        ],
       [0.64934701, 0.0206012 , 0.69027139, 0.64615704, 1.        ],
       [0.89283842, 0.18479588, 0.55289879, 0.96149412, 0.        ],
       [0.24042694, 0.30706434, 0.11506745, 0.66510489, 0.        ],
       [0.09197872, 0.30773599, 0.81091855, 0.66206137, 0.        ],
       [0.91537502, 0.26913929, 0.02676   , 0.62181509, 1.        ],
       [0.09197872, 0.30773599, 0.81091855, 0.66206137, 0.        ]])

# Ex3

In [82]:
idx = [1,2,3,4]
np_matrix[idx,:]


array([[0.64934701, 0.0206012 , 0.69027139, 0.64615704, 0.559575  ],
       [0.09197872, 0.30773599, 0.81091855, 0.66206137, 0.0944198 ],
       [0.24042694, 0.30706434, 0.11506745, 0.66510489, 0.1113399 ],
       [0.89283842, 0.18479588, 0.55289879, 0.96149412, 0.07584279]])

# Ex4

In [83]:
np_matrix = np.random.randint(10,size = (10,5))
np_matrix

array([[1, 1, 6, 9, 5],
       [1, 1, 8, 7, 3],
       [3, 9, 0, 2, 0],
       [2, 8, 5, 3, 2],
       [5, 3, 7, 3, 4],
       [9, 4, 0, 6, 4],
       [7, 5, 0, 7, 9],
       [5, 6, 3, 9, 8],
       [7, 0, 2, 3, 3],
       [7, 1, 6, 3, 4]])

In [84]:
X = np.random.randint(2,size=(10))
X

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 1])

In [85]:
np_matrix[np.where(X[:] == 0)]

array([[1, 1, 6, 9, 5],
       [1, 1, 8, 7, 3],
       [3, 9, 0, 2, 0],
       [2, 8, 5, 3, 2],
       [7, 5, 0, 7, 9],
       [5, 6, 3, 9, 8],
       [7, 0, 2, 3, 3]])

In [86]:
np_matrix[np.where(X[:] == 1)]

array([[5, 3, 7, 3, 4],
       [9, 4, 0, 6, 4],
       [7, 1, 6, 3, 4]])

# Ex5

In [87]:
data = np.random.randint(5,size=(5,5)) + 1
data

array([[4, 5, 2, 5, 3],
       [2, 5, 3, 4, 1],
       [4, 4, 5, 4, 2],
       [2, 1, 3, 1, 5],
       [1, 1, 5, 2, 4]])

In [88]:
-np.sort(data[0,:]*-1)

array([5, 5, 4, 3, 2])

In [89]:
np_test= np.arange(25).reshape(5,5)
np_test

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Ex6

In [90]:
np.arange(0,25,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

# Ex7

In [91]:
np_test[np.diag_indices_from(np_test)] = 0.
np_test

array([[ 0,  1,  2,  3,  4],
       [ 5,  0,  7,  8,  9],
       [10, 11,  0, 13, 14],
       [15, 16, 17,  0, 19],
       [20, 21, 22, 23,  0]])